### ISSUE TITLE
missing parts in from background and blending to foreground 

### ISSUE THREAD

**Issue by ryanmafrty** [layerdiffusion/sd-forge-layerdiffuse#40]
hi, I'm trying the basic functions and noticed that the image generated by "from background and blending to foreground" missed a leg of the generated horse, is it normal or did I do anything wrong? Base model is Juggernaut XL V6
![屏幕截图 2024-03-05 173956](https://github.com/layerdiffusion/sd-forge-layerdiffuse/assets/33319311/0a647271-76a9-4b58-9569-d5a699906c5e)

**Comment by ryanmafrty** [comment]
this missed two legs
![屏幕截图 2024-03-05 174607](https://github.com/layerdiffusion/sd-forge-layerdiffuse/assets/33319311/2c92f786-38d5-4a2a-8c9a-6aec7a9c4362)

**Comment by layerdiffusion** [comment]
i will upload models trained with revised training script soon so that we have less problems with k-diffusions like this

currently if you change the seed/samplers a bit this can be fixed, but it can work much better after i fix some inconsistency between my training script and k-diffusion samplers

also we will very soon upload one-step model and please be patient and come back several days later

**Comment by ryanmafrty** [comment]
Thanks for your quick reply and such good work, will waiting for better version!
